server:
  port: 8802
spring:
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: eureka02
  client:
    fetch-registry: false
    #    register-with-eureka: false
    service-url:
      defaultZone: http://eureka01:8801/eureka
 